version: "3"

services:
  sonarqube:
    image: sonarqube:8.4.2-community
    ports:
      - 9000:9000
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube_db:5432/sonar
    volumes:
      - ./docker/sonarqube/conf:/opt/sonarqube/conf
      - ./docker/sonarqube/data:/opt/sonarqube/data
      - ./docker/sonarqube/extensions:/opt/sonarqube/extensions

  sonarqube_db:
    image: postgres:12.4-alpine
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./docker/sonar_db:/var/lib/postgresql

networks:
  sonarnet:
    driver: bridge
