/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package com.github.fishibashi.nosqlexample

class NoSQLExample {}

object NoSQLExample {
  def main(args: Array[String]): Unit = println("Hello, NoSQL")

  def someLibraryMethod(): Boolean = true
}
