DROP TABLE IF EXISTS ADDRESS;

CREATE TABLE ADDRESS (
  addressCode int not null PRIMARY KEY,
  prefectureCode int ,
  municipalityCode int ,
  areaCode int ,
  zipCode varchar(8) ,
  isOffice int ,
  disabled int ,
  prefecture varchar(255) ,
  prefectureKana varchar(255) ,
  municipality varchar(255) ,
  municipalityKana varchar(255) ,
  area varchar(255) ,
  areaKana varchar(255) ,
  areaAnnotation varchar(255) ,
  kyotoStreetName varchar(255) ,
  block varchar(255) ,
  blockKana varchar(255) ,
  remark varchar(255) ,
  officeName varchar(255) ,
  officeNameKana varchar(255) ,
  officeAddress varchar(255) ,
  newOfficeCode varchar(255)
);

DROP TABLE IF EXISTS REFERENCEVO;

CREATE TABLE REFERENCEVO (
    TASKID              VARCHAR(80) NOT NULL,
    SYSTEMID            VARCHAR(40),
    STARTTIME           VARCHAR(17) NOT NULL,
    ENDTIME             VARCHAR(17),
    TOTALTIME           BIGINT NOT NULL,
    CLIENTIP            VARCHAR(39)
);

CREATE INDEX IDX_REFERENCEVO_1 ON REFERENCEVO (TASKID);
CREATE INDEX IDX_REFERENCEVO_2 ON REFERENCEVO (STARTTIME);
CREATE INDEX IDX_REFERENCEVO_3 ON REFERENCEVO (TOTALTIME);
CREATE INDEX IDX_REFERENCEVO_4 ON REFERENCEVO (SYSTEMID);

DROP TABLE IF EXISTS POINTREFERENCEVO;

CREATE TABLE POINTREFERENCEVO (
    TASKID            VARCHAR(80) NOT NULL,
    REFERENCEID       VARCHAR(80) NOT NULL,
    PARENTREFERENCEID VARCHAR(80),
    POINTCOUNT        BIGINT NOT NULL,
    STARTTIME         VARCHAR(17) NOT NULL,
    ENDTIME           VARCHAR(17),
    TOTALTIME         BIGINT NOT NULL,
    CLASSNAME         VARCHAR(128) NOT NULL,
    METHODNAME        VARCHAR(128) NOT NULL,
    DATATABLE         BYTEA,
    ISSUCCESS         VARCHAR(1)
);

CREATE INDEX IDX_POINTREFERENCEVO_1 ON POINTREFERENCEVO (TASKID);
CREATE INDEX IDX_POINTREFERENCEVO_2 ON POINTREFERENCEVO (STARTTIME);
CREATE INDEX IDX_POINTREFERENCEVO_3 ON POINTREFERENCEVO (REFERENCEID);
CREATE INDEX IDX_POINTREFERENCEVO_4 ON POINTREFERENCEVO (ENDTIME);
CREATE INDEX IDX_POINTREFERENCEVO_5 ON POINTREFERENCEVO (CLASSNAME, METHODNAME);
