CREATE TABLE ADDRESS (
  addressCode int not null PRIMARY KEY,
  prefectureCode int ,
  municipalityCode int ,
  areaCode int ,
  zipCode varchar(8) ,
  isOffice int ,
  disabled int ,
  prefecture varchar(255) ,
  prefectureKana varchar(255) ,
  municipality varchar(255) ,
  municipalityKana varchar(255) ,
  area varchar(255) ,
  areaKana varchar(255) ,
  areaAnnotation varchar(255) ,
  kyotoStreetName varchar(255) ,
  block varchar(255) ,
  blockKana varchar(255) ,
  remark varchar(255) ,
  officeName varchar(255) ,
  officeNameKana varchar(255) ,
  officeAddress varchar(255) ,
  newOfficeCode varchar(255)
);
